version: '3'
services:
  nginx:
    build: _docker/nginx
    ports:
      - "5000:80"
    volumes:
      - ./:/application
      - ./_docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./_docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
  php-fpm:
    build: _docker/php-fpm
    environment:
      BEEJEE_MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./:/application
      - ./_docker/php-fpm/php.ini:/usr/local/etc/php/php.ini
    links:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: beejee
    ports:
      - "6000:3306"
